### ISSUE TITLE
Add Codes in Kotlin Language

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Hacktoberfest_19#40]

**Comment by infiniteoverflow** [comment]
Please provide program files of the fomat file_name.kt

**Comment by Mayank-dev-commits** [comment]
Hello ! can I add single linked program in  c language .

**Comment by LiveWithCS** [comment]
added Kotlin program to Check if Int Array contains a given value  #60

**Comment by infiniteoverflow** [comment]
Thanks !! Happy Hacktoberfest !

**Comment by infiniteoverflow** [comment]
Feel free to contribute

**Comment by LiveWithCS** [comment]
added  Program to Check Palindrome #85
