### ISSUE TITLE
Add codes in JavaScript Folder 

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Hacktoberfest_19#94]

**Comment by naveenIndianCoder** [comment]
Hello, i want to contribute in the javascript folder with a javascript algorithm with its own folder an inherited with a read me a file and solution.js file. Can i do that contribution?

**Comment by infiniteoverflow** [comment]
Feel Free to contribute :)

**Comment by naveenIndianCoder** [comment]
thank you very much : )

**Comment by Sourabh950** [comment]
i have send you a pull request with java script and a directory with bash program in it if it looks good then please merge it

**Comment by naveenIndianCoder** [comment]
Hey, I have made a contribution in your Javascript folder, please accept the pull request and merge it. 🙂🙂
