### ISSUE TITLE
Add a python code that does twitter analysis and returns the details of tweets using a certain hashtags.

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Hacktoberfest_19#95]

**Comment by Sokom141** [comment]
Could you please elaborate more on what's needed exactly? 😄

**Comment by infiniteoverflow** [comment]
I need a code that retrieves tweets that has a certain hashtag

**Comment by rdeleonf** [comment]
What are you expecting as an output?
A JSON, a TXT, a CSV?

Do you want an aggregate analysis of the results?

**Comment by infiniteoverflow** [comment]
The output can be of any type. i need to perform various analysis on the returned data

**Comment by lawaloy** [comment]
can I take on this? or you can fork the code from my repo?

**Comment by infiniteoverflow** [comment]
Please feel free to add ur code :)

**Comment by yash2189** [comment]
Can I take on this?
